package lab11_05_08.parser;


public enum TokenType { // important: BOOL, IDENT, NUM, SKIP and BINARY must have ordinals 1, 2, 3, 4 and 5
	EOF, BOOL, IDENT, NUM, SKIP, BINARY, IN, FOR, PRINT, PREFIX, VAR, PLUS, TIMES, ASSIGN, OPEN_PAR, CLOSE_PAR, STMT_SEP, EXP_SEP, OPEN_BLOCK, CLOSE_BLOCK, MINUS, OPEN_LIST, CLOSE_LIST
}
